nelmio_api_doc:
    documentation:
        servers:
            - url: localhost
              description: API over HTTP
        info:
            title: La Guilde des Seigneurs
            description: API utilisee pour la Guilde des Seigneurs
            version: "0.11"
    areas: # to filter documented areas
        path_patterns:
            - ^/((?!api|_error).*$) # Accepts routes under /api except /api/doc
